In [1]:
import datetime
import pandas as pd

## Go the idea from this guy
## https://www.youtube.com/watch?v=4MbCzUzS0Yo&list=PLqGszNYONKyqOdtV_iQ6NENNA7_mHO7kh&index=2

In [11]:
ticker = 'APPL' 

start_date = str(int(datetime.datetime(2021,10,1).timestamp()))
end_date = str(int(datetime.datetime(2021,10,27).timestamp())) 

interval= '1d'
#'1wk'
#'1mo'
#'1yr'

event ='history'

url = 'https://query1.finance.yahoo.com/v7/finance/download/'\
      + ticker + '?period1=' + start_date + '&period2=' + end_date + '&interval='\
      + interval + '&events=' + event 

#'&includeAdjustedClose=true'

print(url)
print (start_date, end_date)

https://query1.finance.yahoo.com/v7/finance/download/SPY?period1=1633060800&period2=1635307200&interval=1d&events=history
1633060800 1635307200

In [13]:
data = pd.read_csv(url)
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-10-01,430.980011,436.029999,427.230011,434.239990,434.239990,129240100
1,2021-10-04,433.000000,433.959991,426.359985,428.640015,428.640015,128570000
2,2021-10-05,430.239990,435.489990,429.390015,433.100006,433.100006,90682500
3,2021-10-06,429.269989,435.119995,427.540009,434.899994,434.899994,113032200
4,2021-10-07,438.390015,441.679993,438.200012,438.660004,438.660004,72437500
5,2021-10-08,439.480011,439.890015,437.190002,437.859985,437.859985,74492900
6,2021-10-11,437.160004,440.260010,434.619995,434.690002,434.690002,65233300
7,2021-10-12,435.670013,436.100006,432.779999,433.619995,433.619995,71181200
8,2021-10-13,434.709991,436.049988,431.540009,435.179993,435.179993,72974000
9,2021-10-14,439.079987,442.660004,438.579987,442.500000,442.500000,70236800
10,2021-10-15,444.750000,446.260010,444.089996,445.869995,445.869995,66226800
11,2021-10-18,443.970001,447.549988,443.269989,447.190002,447.190002,62213200
12,2021-10-19,448.920013,450.709991,448.269989,450.640015,450.640015,46996800
13,2021-10-20,451.130005,452.730011,451.010010,452.410004,452.410004,49571600
14,2021-10-21,451.769989,453.829987,451.309998,453.589996,453.589996,41305400
15,2021-10-22,453.130005,454.670013,451.049988,453.119995,453.119995,58755900
16,2021-10-25,454.279999,455.899994,452.390015,455.549988,455.549988,45214500
17,2021-10-26,457.200012,458.489990,455.559998,455.959991,455.959991,56075100